name: Publish

on:
  push:
    branches:
      - main

concurrency: release

jobs:
  ci:
    name: Build and test
    uses: ./.github/workflows/ci-all.yml

  release:
    name: Release
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish openapi-tsrf-runtime
        uses: JS-DevTools/npm-publish@v3
        id: publish-openapi-tsrf-runtime
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: artifacts/runtime/package.json
          access: 'public'

      - name: Publish openapi-tsrf-cli
        uses: JS-DevTools/npm-publish@v3
        id: publish-openapi-tsrf-cli
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: artifacts/cli/package.json
          access: 'public'

